import { SupabaseConnectionCard } from "../components/SupabaseConnectionCard";

const frameworks = [
  { name: "EU AI Act", progress: 72, gaps: 12 },
  { name: "DPDPA 2023", progress: 88, gaps: 4 },
  { name: "ISO 42001", progress: 61, gaps: 22 }
];

const complianceHealth = 91;
const ringLength = 2 * Math.PI * 34;
const ringOffset = ringLength * (1 - complianceHealth / 100);

export default function DashboardPage() {
  const hasAiSuggestion = true;

  return (
    <main className="space-y-4">
      <div>
        <h1 className="text-2xl font-bold">aic Privacy Cockpit <span className="muted text-sm">● Live v2.0</span></h1>
        <p className="muted">Good morning, Darpan. Your compliance health is strong. 3 items need attention.</p>
      </div>

      <section className="kpi-grid">
        <div className="card">
          <p className="muted text-sm">AI Systems Monitored</p>
          <p className="text-3xl font-bold">42</p>
          <p className="success text-sm">↑ 3 new</p>
        </div>
        <div className="card">
          <p className="muted text-sm">Active Jurisdictions</p>
          <p className="text-3xl font-bold">07</p>
          <p className="warning text-sm">2 alerts</p>
        </div>
        <div className="card">
          <p className="muted text-sm">Compliance Health</p>
          <div className="flex items-center gap-3">
            <svg className="progress-ring" viewBox="0 0 82 82" role="img" aria-label="Compliance health ring">
              <circle cx="41" cy="41" r="34" fill="none" stroke="#e5e7eb" strokeWidth="8" />
              <circle
                cx="41"
                cy="41"
                r="34"
                fill="none"
                stroke="#10b981"
                strokeWidth="8"
                strokeLinecap="round"
                strokeDasharray={ringLength}
                strokeDashoffset={ringOffset}
                transform="rotate(-90 41 41)"
              />
              <text x="41" y="46" textAnchor="middle" fontSize="16" fontWeight="700">{complianceHealth}%</text>
            </svg>
            <div className="w-full">
              <p className="success text-sm">↑ 4.2% this month</p>
              <svg className="sparkline" viewBox="0 0 120 34" aria-hidden>
                <polyline fill="none" stroke="#2563eb" strokeWidth="2" points="0,24 20,22 40,23 60,16 80,14 100,9 120,6" />
              </svg>
            </div>
          </div>
        </div>
      </section>

      <section className="card">
        <h2 className="font-semibold">⚠️ Action Required (3)</h2>
        <ul className="action-list">
          <li className="warning">DSR-004 expires in 6 days — Arjun Gill (Next of kin)</li>
          <li className="danger">ChestScan AI missing NABH validation protocol</li>
          <li className="warning">EU AI Act: High-risk system assessment overdue</li>
        </ul>
        <div className="flex gap-2">
          <button className="ghost-btn">Review All</button>
          <button className="ghost-btn">Dismiss</button>
        </div>
      </section>

      <section className="two-col">
        {hasAiSuggestion && (
          <div className="card">
            <h2 className="font-semibold">🤖 AI Agent Suggestions</h2>
            <p className="ai-label">Generated by AI · Review suggested</p>
            <p className="muted my-2">"Generate Q2 compliance report for EU AI Act?"</p>
            <div className="flex gap-2">
              <button className="ghost-btn">Generate</button>
              <button className="ghost-btn">Dismiss</button>
            </div>
          </div>
        )}
        <div className="card">
          <h2 className="font-semibold">Quick Actions</h2>
          <ul className="action-list">
            <li>⌘K Classify New AI System</li>
            <li>⌘D Log Data Subject Request</li>
            <li>⌘R Run Framework Assessment</li>
            <li>⌘I Create Incident Report</li>
          </ul>
        </div>
      </section>

      <section className="card">
        <h2 className="font-semibold mb-2">Framework Status</h2>
        {frameworks.map((framework) => (
          <div className="progress-row" key={framework.name}>
            <span>{framework.name}</span>
            <div className="progress-track">
              <div className="progress-fill" style={{ width: `${framework.progress}%` }} />
            </div>
            <span>{framework.progress}% [{framework.gaps} gaps]</span>
          </div>
        ))}
      </section>

      <SupabaseConnectionCard />
    </main>
  );
}
