const frameworkRows = {
  critical: [
    { framework: "NIST AI RMF", progress: 55, controls: "44/80", risk: "High" },
    { framework: "ISO 42001", progress: 61, controls: "32/52", risk: "High" }
  ],
  open: [
    { framework: "EU AI Act 2024", progress: 72, controls: "49/68", risk: "Medium" },
    { framework: "CDSCO SaMD", progress: 80, controls: "33/41", risk: "Medium" }
  ],
  compliant: [
    { framework: "DPDPA 2023", progress: 88, controls: "30/34", risk: "Low" },
    { framework: "NABH Clinical AI", progress: 95, controls: "27/28", risk: "Low" }
  ]
};

export default function CompliancePage() {
  return (
    <main className="space-y-4">
      <div>
        <h1 className="text-2xl font-bold">FRAMEWORK COMPLIANCE</h1>
        <p className="muted">Manage regulatory obligations across jurisdictions</p>
      </div>

      <section className="kpi-grid">
        <div className="card"><p className="muted text-sm">OVERALL HEALTH</p><p className="text-3xl font-bold">87%</p><p className="success text-sm">▲ +3% vs last month</p></div>
        <div className="card"><p className="muted text-sm">FRAMEWORKS ACTIVE</p><p className="text-3xl font-bold">6</p></div>
        <div className="card"><p className="muted text-sm">CONTROLS ASSESSED</p><p className="text-3xl font-bold">142/198</p></div>
      </section>

      <section className="card">
        <div className="flex gap-2 flex-wrap mb-3">
          <button className="ghost-btn">Active Frameworks</button>
          <button className="ghost-btn">Control Library</button>
          <button className="ghost-btn">Mappings</button>
          <button className="ghost-btn">Gap</button>
        </div>
        <div className="overflow-x-auto" style={{ maxHeight: 320 }}>
          <table className="data-table">
            <thead>
              <tr className="text-left">
                <th className="py-2">Framework</th><th>Progress</th><th>Controls</th><th>Risk</th><th>Status</th>
              </tr>
            </thead>
            <tbody>
              <tr><td colSpan={5} className="py-2 font-semibold danger">Critical / Open</td></tr>
              {[...frameworkRows.critical, ...frameworkRows.open].map((row) => (
                <tr key={row.framework}>
                  <td className="py-2">{row.framework}</td>
                  <td>{row.progress}%</td>
                  <td>{row.controls}</td>
                  <td>{row.risk}</td>
                  <td><span className="pill active">● Active</span></td>
                </tr>
              ))}
              <tr><td colSpan={5} className="py-2 font-semibold success">Compliant</td></tr>
              {frameworkRows.compliant.map((row) => (
                <tr key={row.framework}>
                  <td className="py-2">{row.framework}</td>
                  <td>{row.progress}%</td>
                  <td>{row.controls}</td>
                  <td>{row.risk}</td>
                  <td><span className="pill active">● Active</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="card">
        <div className="flex gap-2 mb-3">
          <button className="ghost-btn">Run Assessment</button>
          <button className="ghost-btn">View Gap Analysis</button>
          <button className="ghost-btn">Generate Report</button>
        </div>
        <h2 className="font-semibold">🤖 AI Agent Activity</h2>
        <p className="ai-label">Generated by AI · Review suggested</p>
        <ul className="action-list">
          <li>Generated ISO 42001 gap analysis (2h ago)</li>
          <li>Mapped DPDPA §8 → GDPR Art. 7 (5h ago)</li>
        </ul>
      </section>
    </main>
  );
}
